modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
issueTrackerURL="https://github.com/lck3000/PearPhoneMod/issues"

[[mods]]
    modId="pearphone"
    version="${file.jarVersion}"
    displayName="PearPhone"
    logoFile="pearphone.png"
    displayURL="https://github.com/lck3000/PearPhoneMod"
    authors="lck3000"
    description='''
A phone mod that adds apps such as an audio player, camera, and more.
Stream YouTube audio to nearby players via proximity-based sound distribution.
Powered by yt-dlp.
'''

[[dependencies.pearphone]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pearphone]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
